# Generated by Django 3.0.5 on 2020-05-24 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('campus_id', models.ManyToManyField(related_name='campus_id', to='election.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.DateField(default=datetime.datetime.today)),
                ('election_start', models.DateTimeField(blank=True, null=True)),
                ('election_end', models.DateTimeField(blank=True, null=True)),
                ('voter_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('sort_number', models.IntegerField()),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionType')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=70)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionType')),
            ],
        ),
        migrations.CreateModel(
            name='MajorPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('date_candidacy', models.DateTimeField(default=datetime.datetime.now)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Party')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.ElectionType'),
        ),
        migrations.CreateModel(
            name='Disqualify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('date_candidacy', models.DateTimeField(default=datetime.datetime.now)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Campus')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.College')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('election_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.ElectionType')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Party')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
        migrations.CreateModel(
            name='CiscVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=100)),
                ('vote_date', models.DateTimeField(blank=True, null=True)),
                ('vote', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.College')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Campus')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.College')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Party')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('date_candidacy', models.DateTimeField(default=datetime.datetime.now)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Campus')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.College')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionType')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
    ]
