# Generated by Django 3.0.5 on 2020-04-27 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.IntegerField(max_length=50)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
    ]
