# Generated by Django 3.0.5 on 2020-05-23 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='election_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.ElectionType'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Disqualify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('date_candidacy', models.DateTimeField(default=datetime.datetime.now)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Campus')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.College')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('election_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.ElectionType')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Party')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
    ]
