# Generated by Django 3.0.5 on 2020-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='campus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
