# Generated by Django 3.0.5 on 2020-04-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_sortposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortposition',
            name='sort_number',
            field=models.IntegerField(),
        ),
    ]
