# Generated by Django 3.0.5 on 2020-04-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20200427_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SortPosition',
        ),
    ]
