# Generated by Django 3.0.5 on 2020-04-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_delete_sortposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='sort_number',
            field=models.IntegerField(default=1),
        ),
    ]
