# Generated by Django 3.0.5 on 2020-05-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_remove_ciscvoter_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=100)),
                ('candidate', models.IntegerField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_date', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
            ],
        ),
    ]
