# Generated by Django 3.0.5 on 2020-04-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_position_sort_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='sort_number',
            field=models.IntegerField(),
        ),
    ]
