# Generated by Django 3.0.5 on 2020-05-04 02:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20200427_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('date_candidacy', models.DateTimeField(default=datetime.datetime.today)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Party')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('date_candidacy', models.DateTimeField(default=datetime.datetime.today)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Campus')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.College')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
    ]
