# Generated by Django 3.0.5 on 2020-05-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_summaryvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryvotes',
            name='vote_count',
        ),
    ]
