# Generated by Django 3.0.5 on 2020-05-05 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_boardmember_majorposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='date_candidacy',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
