# Generated by Django 3.0.5 on 2020-05-29 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_studentvoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryvotes',
            name='vote_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
