# Generated by Django 3.0.5 on 2020-05-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20200529_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryvotes',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.Position'),
            preserve_default=False,
        ),
    ]
