# Generated by Django 3.0.5 on 2020-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20200505_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='campus_id',
        ),
        migrations.AddField(
            model_name='college',
            name='campus',
            field=models.ManyToManyField(related_name='campus_id', to='election.Campus'),
        ),
    ]
