# Generated by Django 3.0.5 on 2020-05-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20200505_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='campus',
            new_name='campus_id',
        ),
    ]
