# Generated by Django 3.0.5 on 2020-05-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20200505_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiscVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=100)),
                ('vote_date', models.DateTimeField(blank=True, null=True)),
                ('vote', models.BooleanField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.College')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
    ]
