# Generated by Django 3.0.5 on 2020-05-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20200512_2109'),
        ('election', '0013_auto_20200508_2213'),
    ]

    operations = [
    ]
