# Generated by Django 3.0.5 on 2020-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0014_merge_20200512_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciscvoter',
            name='student_number',
            field=models.CharField(default=-103853, max_length=100),
            preserve_default=False,
        ),
    ]
