from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='election-home'),
    #create ssc elections
    path('create/<str:name>/<int:id>/', views.create, name='create-form'),
    path('save/', views.saveCandidateForm, name='save-ssc-form'),
    #view of list utilities
    path('utilities/', views.utilities, name='view-utilities'),
    #CRUD for Campus
    path('utilities/campus_utilities/edit/', 
    	views.createUtilitiesCampus, 
    	name='campus-edit'),
    path('utilities/campus_utilities/add/',
    	views.saveUtilitiesCampus, 
    	name='campus-add'),
    path('utilities/campus_utilities/<int:id>/update/',
        views.updateUtilitiesCampus, 
        name='campus-update'),
    path('utilities/campus_utilities/<int:id>/delete/',
        views.deleteUtilitiesCampus, 
        name='campus-delete'),
    #CRUD for college
    path('utilities/college_utilities/edit', 
        views.createUtilitiesCollege, 
        name='college-edit'),
    path('utilities/college_utilities/edit/<int:id>/', 
        views.filterUtilitiesCollege, 
        name='college-edit-filter'),
    path('utilities/college_utilities/add/',
        views.saveUtilitiesCollege, 
        name='college-add'),
    path('utilities/college_utilities/<int:id>/update/',
        views.updateUtilitiesCollege, 
        name='college-update'),
    path('utilities/college_utilities/<int:id>/delete/',
        views.deleteUtilitiesCollege, 
        name='college-delete'),
    #CRUD for Election
    path('utilities/election_utilities/edit/', 
        views.createUtilitiesElection, 
        name='election-edit'),
    path('utilities/election_utilities/add/',
        views.saveUtilitiesElection, 
        name='election-add'),
    path('utilities/election_utilities/<int:id>/update/',
        views.updateUtilitiesElection, 
        name='election-update'),
    path('utilities/election_utilities/<int:id>/delete/',
        views.deleteUtilitiesElection, 
        name='election-delete'),
    #CRUD for position
    path('utilities/position_utilities/edit', 
        views.createUtilitiesPosition, 
        name='position-edit'),
    path('utilities/position_utilities/edit/<int:id>/', 
        views.filterUtilitiesPosition, 
        name='position-edit-filter'),
    path('utilities/position_utilities/add/',
        views.saveUtilitiesPosition, 
        name='position-add'),
    path('utilities/position_utilities/<int:id>/update/',
        views.updateUtilitiesPosition, 
        name='position-update'),
    path('utilities/position_utilities/<int:id>/delete/',
        views.deleteUtilitiesPosition, 
        name='position-delete'),
    path('test/', views.saveDesign, 
    	name='create-utilities-position'),
]